### ISSUE TITLE
Transcoder (ffmpeg) immediately dies

### ISSUE THREAD

**Issue by davidjameshowell** [UnicornTranscoder/UnicornTranscoder#46] opened 2019-03-06 09:08 UTC
Everything appears to be working well for me, up until the remote transcoder.

For context:

This is Dockerized and contains Node 8, RClone, UnicornTranscoder, and S6 for service start and config. UnicornTranscoder installs fine, starts up, and receives events from the load balancer.

The issue appears to be that immediately after starting the transcoder it does, with no indication as to why. I had a thought that it might have been path names not being escaped, so I moved the "Plex Transcoder" to "PlexTranscoder", set my env appropriately, and retested with no avail. I can run the commands within the container as the specified user and receive output:

`
/opt/UnicornTranscoder/plexmediaserver/1.14.1.5488-cc260c476/usr/lib/plexmediaserver/PlexTranscoder -codec:0 h264 -codec:1 dca -probesize 10000000 -i "/RCloneMedia/Movies/A Movie With Spaces/A Movie With Spaces [Remux-1080p].mkv" -filter_complex [0:0]scale=w=1920:h=1080[0];[0]format=pix_fmts=yuv420p|nv12[1] -filter_complex [0:1] aresample=async=1:ocl='stereo':osr=48000[2] -map [1] -codec:0 libx264 -crf:0 23 -maxrate:0 7393k -bufsize:0 14786k -r:0 23.975999999999999 -preset:0 veryfast -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 expr:gte\(t,0+n_forced*1\) -map [2] -metadata:s:1 language=eng -codec:1 aac -b:1 109k -f dash -min_seg_duration 1000000 -skip_to_segment 1 -time_delta 0.0625 -manifest_name http://127.0.0.1:32400/video/:/transcode/session/SESSIONID/9b573be0-1a02-4c04-9f51-7de22cca966a/manifest -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 dash -start_at_zero -copyts -vsync cfr -y -nostats -loglevel quiet -loglevel_plex error -progressurl http://127.0.0.1:32400/video/:/transcode/session/SESSIONID/4b3a0fa3-5e02-432b-b71d-d12fadfc7143/progress`

In my last attempt, I have been rewritting to regex certain parameters which appear to be unescaped and causing the failure

`
.replace('{INTERNAL_TRANSCODER}', "http://127.0.0.1:" + config.port + '/')
                            .replace('{INTERNAL_RESOURCES}', PlexDirectories.getPlexResources())
                            .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/seglist/, this.uuid + '/seglist')
                            .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/manifest/, this.uuid + '/manifest')
                            .replace(/(\/RCloneMedia\/[a-zA-z0-9\/].*\.[a-zA-Z]{3})/g, '"$1"')
                            .replace(/(expr:gte\(.*\))/g, '"$1"')
                            .replace(/(-filter_complex\s[\S]*)/g, '"$1"')
`

producing:

```
2019-03-06T08:31:12.679Z UnicornTranscoder:Dash 3g8jprmvg3osn5stz4ejc8ca
2019-03-06T08:31:12.680Z UnicornTranscoder:Transcoder Create transcoder 3g8jprmvg3osn5stz4ejc8ca
2019-03-06T08:31:12.682Z UnicornTranscoder:SessionManager save 3g8jprmvg3osn5stz4ejc8ca
2019-03-06T08:31:12.934Z UnicornTranscoder:Transcoder -codec:0
2019-03-06T08:31:12.935Z UnicornTranscoder:Transcoder h264
2019-03-06T08:31:12.936Z UnicornTranscoder:Transcoder -codec:1
2019-03-06T08:31:12.936Z UnicornTranscoder:Transcoder truehd_eae
2019-03-06T08:31:12.936Z UnicornTranscoder:Transcoder -eae_prefix:1
2019-03-06T08:31:12.937Z UnicornTranscoder:Transcoder 3g8jprmvg3osn5stz4ejc8ca_
2019-03-06T08:31:12.937Z UnicornTranscoder:Transcoder -probesize
2019-03-06T08:31:12.937Z UnicornTranscoder:Transcoder 10000000
2019-03-06T08:31:12.937Z UnicornTranscoder:Transcoder -i
2019-03-06T08:31:12.937Z UnicornTranscoder:Transcoder "/RCloneMedia/Movies/13 Going on 30 (2004)/13 Going on 30 (2004) [Remux-1080p].mkv"
2019-03-06T08:31:12.938Z UnicornTranscoder:Transcoder -filter_complex
2019-03-06T08:31:12.938Z UnicornTranscoder:Transcoder [0:0]scale=w=1280:h=720[0];[0]format=pix_fmts=yuv420p|nv12[1]
2019-03-06T08:31:12.938Z UnicornTranscoder:Transcoder -filter_complex
2019-03-06T08:31:12.938Z UnicornTranscoder:Transcoder [0:1] aresample=async=1:ocl='stereo':osr=48000[2]
2019-03-06T08:31:12.939Z UnicornTranscoder:Transcoder -map
2019-03-06T08:31:12.939Z UnicornTranscoder:Transcoder [1]
2019-03-06T08:31:12.939Z UnicornTranscoder:Transcoder -metadata:s:0
2019-03-06T08:31:12.939Z UnicornTranscoder:Transcoder language=eng
2019-03-06T08:31:12.939Z UnicornTranscoder:Transcoder -codec:0
2019-03-06T08:31:12.940Z UnicornTranscoder:Transcoder libx264
2019-03-06T08:31:12.940Z UnicornTranscoder:Transcoder -crf:0
2019-03-06T08:31:12.940Z UnicornTranscoder:Transcoder 23
2019-03-06T08:31:12.940Z UnicornTranscoder:Transcoder -maxrate:0
2019-03-06T08:31:12.941Z UnicornTranscoder:Transcoder 3676k
2019-03-06T08:31:12.941Z UnicornTranscoder:Transcoder -bufsize:0
2019-03-06T08:31:12.941Z UnicornTranscoder:Transcoder 7352k
2019-03-06T08:31:12.941Z UnicornTranscoder:Transcoder -r:0
2019-03-06T08:31:12.941Z UnicornTranscoder:Transcoder 23.975999999999999
2019-03-06T08:31:12.941Z UnicornTranscoder:Transcoder -preset:0
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder veryfast
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -x264opts:0
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -force_key_frames:0
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder "expr:gte(t,0+n_forced*3)"
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -map
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder [2]
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -metadata:s:1
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder language=eng
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -codec:1
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder aac
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -b:1
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder 119k
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -f
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder dash
2019-03-06T08:31:12.942Z UnicornTranscoder:Transcoder -min_seg_duration
2019-03-06T08:31:12.943Z UnicornTranscoder:Transcoder 3000000
2019-03-06T08:31:12.943Z UnicornTranscoder:Transcoder -skip_to_segment
2019-03-06T08:31:12.943Z UnicornTranscoder:Transcoder 1
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -time_delta
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder 0.0625
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -manifest_name
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder http://127.0.0.1:32400/video/:/transcode/session/3g8jprmvg3osn5stz4ejc8ca/7217c123-388a-422b-a03f-b3bc7578055b/manifest
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -avoid_negative_ts
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder disabled
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -map_metadata
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -1
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -map_chapters
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -1
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder dash
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -start_at_zero
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -copyts
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -vsync
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder cfr
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -y
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -nostats
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -loglevel
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder quiet
2019-03-06T08:31:12.944Z UnicornTranscoder:Transcoder -loglevel_plex
2019-03-06T08:31:12.945Z UnicornTranscoder:Transcoder error
2019-03-06T08:31:12.945Z UnicornTranscoder:Transcoder -progressurl
2019-03-06T08:31:12.945Z UnicornTranscoder:Transcoder http://127.0.0.1:32400/video/:/transcode/session/3g8jprmvg3osn5stz4ejc8ca/4fa300a8-823e-4c60-a875-be28dcb03d81/progress
2019-03-06T08:31:12.946Z UnicornTranscoder:Transcoder Spawn 3g8jprmvg3osn5stz4ejc8ca
2019-03-06T08:31:12.946Z UnicornTranscoder:Transcoder [ '-codec:0',
  'h264',
  '-codec:1',
  'truehd_eae',
  '-eae_prefix:1',
  '3g8jprmvg3osn5stz4ejc8ca_',
  '-probesize',
  '10000000',
  '-i',
  '"/RCloneMedia/Movies/A Movie With Space (2004)/A Movie With Space (2004) [Remux-1080p].mkv"',
  '-filter_complex',
  '[0:0]scale=w=1280:h=720[0];[0]format=pix_fmts=yuv420p|nv12[1]',
  '-filter_complex',
  '[0:1] aresample=async=1:ocl=\'stereo\':osr=48000[2]',
  '-map',
  '[1]',
  '-metadata:s:0',
  'language=eng',
  '-codec:0',
  'libx264',
  '-crf:0',
  '23',
  '-maxrate:0',
  '3676k',
  '-bufsize:0',
  '7352k',
  '-r:0',
  '23.975999999999999',
  '-preset:0',
  'veryfast',
  '-x264opts:0',
  'subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none',
  '-force_key_frames:0',
  '"expr:gte(t,0+n_forced*3)"',
  '-map',
  '[2]',
  '-metadata:s:1',
  'language=eng',
  '-codec:1',
  'aac',
  '-b:1',
  '119k',
  '-f',
  'dash',
  '-min_seg_duration',
  '3000000',
  '-skip_to_segment',
  '1',
  '-time_delta',
  '0.0625',
  '-manifest_name',
  'http://127.0.0.1:32400/video/:/transcode/session/3g8jprmvg3osn5stz4ejc8ca/7217c123-388a-422b-a03f-b3bc7578055b/manifest',
  '-avoid_negative_ts',
  'disabled',
  '-map_metadata',
  '-1',
  '-map_chapters',
  '-1',
  'dash',
  '-start_at_zero',
  '-copyts',
  '-vsync',
  'cfr',
  '-y',
  '-nostats',
  '-loglevel',
  'quiet',
  '-loglevel_plex',
  'error',
  '-progressurl',
  'http://127.0.0.1:32400/video/:/transcode/session/3g8jprmvg3osn5stz4ejc8ca/4fa300a8-823e-4c60-a875-be28dcb03d81/progress' ]
ffmpeg version git-2018-09-24-531e313 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.2 (GCC)
  configuration: --libdir=/data/jenkins/pms-deps-universal-v2/BUILD_TAG/linux-ubuntu-x86_64/output/pms-depends-linux-ubuntu-x86_64-release-79dcc0f/lib --prefix=/data/jenkins/pms-deps-universal-v2/BUILD_TAG/linux-ubuntu-x86_64/output/pms-depends-linux-ubuntu-x86_64-release-79dcc0f --disable-bzlib --disable-ffplay --disable-ffprobe --disable-avdevice --disable-schannel --disable-linux-perf --disable-mediacodec --disable-debug --disable-doc --disable-shared --pkg-config-flags=--static --enable-muxers --enable-gpl --enable-version3 --enable-gnutls --enable-eae --disable-encoders --disable-decoders --disable-hwaccels --enable-libass --enable-librtmp --disable-devices --disable-lzma --disable-iconv --disable-protocol=concat --enable-libvorbis --enable-libopus --external-decoder=h264 --disable-bsfs --enable-bsf='aac_adtstoasc,extract_extradata,dca_core,h264_mp4toannexb,hevc_mp4toannexb,vp9_superframe,vp9_superframe_split,framedrop' --enable-decoder=png --enable-decoder=apng --enable-decoder=bmp --enable-decoder=mjpeg --enable-decoder=thp --enable-decoder=gif --enable-decoder=dirac --enable-decoder=ffv1 --enable-decoder=ffvhuff --enable-decoder=huffyuv --enable-decoder=rawvideo --enable-decoder=zero12v --enable-decoder=ayuv --enable-decoder=r210 --enable-decoder=v210 --enable-decoder=v210x --enable-decoder=v308 --enable-decoder=v408 --enable-decoder=v410 --enable-decoder=y41p --enable-decoder=yuv4 --enable-decoder=ansi --enable-decoder=alac --enable-decoder=flac --enable-decoder=vorbis --enable-decoder=opus --enable-decoder=pcm_f32be --enable-decoder=pcm_f32le --enable-decoder=pcm_f64be --enable-decoder=pcm_f64le --enable-decoder=pcm_lxf --enable-decoder=pcm_s16be --enable-decoder=pcm_s16be_planar --enable-decoder=pcm_s16le --enable-decoder=pcm_s16le_planar --enable-decoder=pcm_s24be --enable-decoder=pcm_s24le --enable-decoder=pcm_s24le_planar --enable-decoder=pcm_s32be --enable-decoder=pcm_s32le --enable-decoder=pcm_s32le_planar --enable-decoder=pcm_s8 --enable-decoder=pcm_s8_planar --enable-decoder=pcm_u16be --enable-decoder=pcm_u16le --enable-decoder=pcm_u24be --enable-decoder=pcm_u24le --enable-decoder=pcm_u32be --enable-decoder=pcm_u32le --enable-decoder=pcm_u8 --enable-decoder=pcm_alaw --enable-decoder=pcm_mulaw --enable-decoder=ass --enable-decoder=dvbsub --enable-decoder=dvdsub --enable-decoder=ccaption --enable-decoder=pgssub --enable-decoder=jacosub --enable-decoder=microdvd --enable-decoder=movtext --enable-decoder=mpl2 --enable-decoder=pjs --enable-decoder=realtext --enable-decoder=sami --enable-decoder=ssa --enable-decoder=stl --enable-decoder=subrip --enable-decoder=subviewer --enable-decoder=text --enable-decoder=vplayer --enable-decoder=webvtt --enable-decoder=xsub --enable-decoder=libzvbi_teletext --enable-decoder=eac3_eae --enable-decoder=truehd_eae --enable-decoder=mlp_eae --enable-encoder=flac --enable-encoder=alac --enable-encoder=libvorbis --enable-encoder=libopus --enable-encoder=mjpeg --enable-encoder=wrapped_avframe --enable-encoder=ass --enable-encoder=dvbsub --enable-encoder=dvdsub --enable-encoder=movtext --enable-encoder=ssa --enable-encoder=subrip --enable-encoder=text --enable-encoder=webvtt --enable-encoder=xsub --enable-encoder=pcm_f32be --enable-encoder=pcm_f32le --enable-encoder=pcm_f64be --enable-encoder=pcm_f64le --enable-encoder=pcm_s8 --enable-encoder=pcm_s8_planar --enable-encoder=pcm_s16be --enable-encoder=pcm_s16be_planar --enable-encoder=pcm_s16le --enable-encoder=pcm_s16le_planar --enable-encoder=pcm_s24be --enable-encoder=pcm_s24le --enable-encoder=pcm_s24le_planar --enable-encoder=pcm_s32be --enable-encoder=pcm_s32le --enable-encoder=pcm_s32le_planar --enable-encoder=pcm_u8 --enable-encoder=pcm_u16be --enable-encoder=pcm_u16le --enable-encoder=pcm_u24be --enable-encoder=pcm_u24le --enable-encoder=pcm_u32be --enable-encoder=pcm_u32le --enable-encoder=h264_vaapi --enable-encoder=hevc_vaapi --enable-encoder=h264_nvenc --enable-encoder=eac3_eae --arch=x86_64 --enable-libzvbi --cc='ccache gcc' --extra-ldflags=-L/data/jenkins/pms-deps-universal-v2/BUILD_TAG/linux-ubuntu-x86_64/output/pms-depends-linux-ubuntu-x86_64-release-79dcc0f/lib --extra-libs='-lgcrypt -lgpg-error -ldl'
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 12.102 / 58. 12.102
  libavformat    58.  9.100 / 58.  9.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100

[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 8 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 9 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 10 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40]
Could not find codec parameters for stream 11 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 12 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 13 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 17 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 18 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 19 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from '/RCloneMedia/Movies/A Movie With Space (2004)/A Movie With Space (2004) [Remux-1080p].mkv':
  Metadata:
    title           : A Movie With Space
    encoder         : libmakemkv v1.7.1 (1.2.0/1.1.0) win(x64-release)
    creation_time   : 2014-05-04T07:44:12.000000Z
  Duration: 01:37:47.86, start: 0.000000, bitrate: 29096 kb/s
    Chapter #0:0: start 0.000000, end 358.066000
    Metadata:
      title           : Chapter 00
    Chapter #0:1: start 358.066000, end 751.041000
    Metadata:
      title           : Chapter 01
    Chapter #0:2: start 751.041000, end 1130.753978
    Metadata:
      title           : Chapter 02
    Chapter #0:3: start 1130.753978, end 1536.076000
    Metadata:
      title           : Chapter 03
    Chapter #0:4: start 1536.076000, end 1747.454000
    Metadata:
      title           : Chapter 04
    Chapter #0:5: start 1747.454000, end 2035.658000
    Metadata:
      title           : Chapter 05
    Chapter #0:6: start 2035.658000, end 2487.860000
    Metadata:
      title           : Chapter 06
    Chapter #0:7: start 2487.860000, end 2802.424000
    Metadata:
      title           : Chapter 07
    Chapter #0:8: start 2802.424000, end 3129.626000
    Metadata:
      title           : Chapter 08
    Chapter #0:9: start 3129.626000, end 3385.340000
    Metadata:
      title           : Chapter 09
    Chapter #0:10: start 3385.340000, end 3794.957000
    Metadata:
      title           : Chapter 10
    Chapter #0:11: start 3794.957000, end 4236.106000
    Metadata:
      title           : Chapter 11
    Chapter #0:12: start 4236.106000, end 4605.684000
    Metadata:
      title           : Chapter 12
    Chapter #0:13: start 4605.684000, end 5054.131978
    Metadata:
      title           : Chapter 13
    Chapter #0:14: start 5054.131978, end 5473.676000
    Metadata:
      title           : Chapter 14
    Chapter #0:15: start 5473.676000, end 5867.862000
    Metadata:
      title           : Chapter 15
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: truehd, 48000 Hz, 5.1(side), s32 (24 bit) (default)
    Metadata:
      title           : 5.1
    Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle (default)
    Stream #0:3(eng): Subtitle: hdmv_pgs_subtitle
    Stream #0:4(kor): Subtitle: hdmv_pgs_subtitle
    Stream #0:5(kor): Subtitle: hdmv_pgs_subtitle
    Stream #0:6(kor): Subtitle: hdmv_pgs_subtitle
    Stream #0:7(ell): Subtitle: hdmv_pgs_subtitle
    Stream #0:8(hin): Subtitle: hdmv_pgs_subtitle
    Stream #0:9(isl): Subtitle: hdmv_pgs_subtitle
    Stream #0:10(pol): Subtitle: hdmv_pgs_subtitle
    Stream #0:11(ron): Subtitle: hdmv_pgs_subtitle
    Stream #0:12(rus): Subtitle: hdmv_pgs_subtitle
    Stream #0:13(tur): Subtitle: hdmv_pgs_subtitle
    Stream #0:14(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Stream #0:15(ita): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Stream #0:16(spa): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Stream #0:17(eng): Subtitle: hdmv_pgs_subtitle
    Stream #0:18(ita): Subtitle: hdmv_pgs_subtitle
    Stream #0:19(spa): Subtitle: hdmv_pgs_subtitle
Filter scale has an unconnected output

/bin/sh: 1: [0]format=pix_fmts=yuv420p: not found

/bin/sh: 1: nv12[1]: not found

2019-03-06T08:31:13.573Z UnicornTranscoder:Transcoder FFMPEG stopped 3g8jprmvg3osn5stz4ejc8ca 127 null
```

Is it possible that during the argument, they are becoming unescaped and causing this failure? If I escape the required parameters (and append for an output), it will begin transcoding a file.

Let me know if you need more explanation! Hoping to come up with a solution!

**Comment by Maxou44** [comment] 2019-03-06 09:15
Thanks for logs, it looks like a subtitle codec issue (cc @drouarb )

```[matroska,webm @ 0x18a5b40] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size```

Can you:
- Try with another file with disabled subtitles?
- Check if this file works with the original PMS?

**Comment by Maxou44** [comment] 2019-03-06 09:25
My bad, the ffmpeg command you ran is incorrect, some parameters have spaces in it or a pipe (values after -complex-filter), add quotes for theses parameters and retry:

`-filter_complex "[0:0]scale=w=1920:h=1080[0];[0]format=pix_fmts=yuv420p|nv12[1]" -filter_complex "[0:1] aresample=async=1:ocl='stereo':osr=48000[2]" -map [1]`

**Comment by davidjameshowell** [comment] 2019-03-06 09:44
To clarify - these files work with regular plex unabated and are in the same format (and directory structure as my current Plex farm is). 

The commands with the spaces are actually directly from the Plex Transcode. I was using ps aux inside the container to grab the full command that was being ran by the process spawn to diagnose further. The first initial failure I get without any regex replacements is a failure on ")" which correlates to my media input path. 

In your testing, have you seen behavior where there are ubescaoed values being passed to process spawning? It's my understanding that process spawning will escape these as part of Node's structuring. 

Is there something more I can do in terms of debugging to potentially provide clearer/directed logs in regards to the issue?

Can you provide an example of an environment you are using for the transcode that I can possibly replicate (using this base image for s6 overlay - https://github.com/linuxserver/docker-baseimage-ubuntu/blob/master/README.md).

I'm so close to getting it working and just hung up by these last pieces! Appreciate the work and followed since your initial release!

**Comment by davidjameshowell** [comment] 2019-03-06 09:53
Would a screen recording of the behavior with logs (Plex and XHR) present be useful in diagnostic?

**Comment by Maxou44** [comment] 2019-03-06 10:15
The UnicornTranscoder runs since 2 years on our servers and we never had issues about arguments escaping, I think the issue isn't here.

The transcoder was correctly installed with a `npm run install` ? No issues with that ?  
The 32400 port was correctly dropped ?

I'm not sure of the behavior of the transcoder after the renaming of the ffmpeg binary  ("PlexTranscoder" instead of "Plex Transcoder") can you revert this changes ?

It could be nice if you can restart your command without the escaping issues, I think ffmpeg will give us the right information 😊

The right command: 
```
./Plex Transcoder"-codec:0" "h264" "-codec:1" "truehd_eae" "-eae_prefix:1" "3g8jprmvg3osn5stz4ejc8ca_" "-probesize" "10000000" "-i" ""/RCloneMedia/Movies/A Movie With Space (2004)/A Movie With Space (2004) [Remux-1080p].mkv"" "-filter_complex" "[0:0]scale=w=1280:h=720[0];[0]format=pix_fmts=yuv420p|nv12[1]" "-filter_complex" "[0:1] aresample=async=1:ocl='stereo':osr=48000[2]" "-map" "[1]" "-metadata:s:0" "language=eng" "-codec:0" "libx264" "-crf:0" "23" "-maxrate:0" "3676k" "-bufsize:0" "7352k" "-r:0" "23.975999999999999" "-preset:0" "veryfast" "-x264opts:0" "subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none" "-force_key_frames:0" ""expr:gte(t,0+n_forced*3)"" "-map" "[2]" "-metadata:s:1" "language=eng" "-codec:1" "aac" "-b:1" "119k" "-f" "dash" "-min_seg_duration" "3000000" "-skip_to_segment" "1" "-time_delta" "0.0625" "-manifest_name" "http://127.0.0.1:32400/video/:/transcode/session/3g8jprmvg3osn5stz4ejc8ca/7217c123-388a-422b-a03f-b3bc7578055b/manifest" "-avoid_negative_ts" "disabled" "-map_metadata" "-1" "-map_chapters" "-1" "dash" "-start_at_zero" "-copyts" "-vsync" "cfr" "-y" "-nostats" "-loglevel" "quiet" "-loglevel_plex" "error" "-progressurl" "http://127.0.0.1:32400/video/:/transcode/session/3g8jprmvg3osn5stz4ejc8ca/4fa300a8-823e-4c60-a875-be28dcb03d81/progress"
```

**Comment by drouarb** [comment] 2019-03-06 10:45
When you execute a child process in NodeJS, you don't need to escape anything since the arguments are in an array, escaping is for shell prompts because they need to transform a string into an array.
If FFMPEG run and ffmpeg stopped exit 1 and null instantly, it means something went wrong, either an argument or a missing codec.
The best way to test is enable log in FFMPEG and redirect it to the output of UnicornTranscoder, for this you need to remove `-loglevel quiet` and an event listener for the stdout.

So here is how to proceed, just after
```js
                        return arg
                            .replace('{INTERNAL_TRANSCODER}', "http://127.0.0.1:" + config.port + '/')
                            .replace('{INTERNAL_RESOURCES}', PlexDirectories.getPlexResources())
                            .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/seglist/, this.uuid + '/seglist')
                            .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/manifest/, this.uuid + '/manifest')
                    });
```
add:
```js
this.transcoderArgs.splice(this.transcoderArgs.indexOf('-loglevel'), 2);
```
and just after:
```js
        this.ffmpeg.on("exit", (code, sig) => {
            debug('FFMPEG stopped ' + this.sessionId + ' ' + code + ' ' + sig);
            this.transcoding = false
        });
```
add
```js
        this.ffmpeg.stdout.on('data', (data) => { console.log('stdout: ' + data.toString()); });
        this.ffmpeg.stderr.on('data', (data) => { console.log('stderr: ' + data.toString()); });
```

Rerun your session, FFMPEG Logs should appear in UnicornTranscoder output log. Se should have more informations on the problem.

**Comment by davidjameshowell** [comment] 2019-03-06 16:48
Okay, I'll add in that and rerun and test and see where that leaves me. I'll additional rebuild and check the container to make sure there's nothing on that end as well. 

WIll be back with logs shortly! Thanks!

**Comment by davidjameshowell** [comment] 2019-03-06 20:03
So that was the key - my troubleshooting efforts were misdirected due to the error dialog I had been trying with.

After attempting with the debug you provided, I was able to isolate the error down to the manifest generation and cannot connect to port 32400.

I ended up just dropping my Node port to 32400 to test and it worked successfully!

**Comment by Maxou44** [comment] 2019-03-06 20:07
Because you launched the load balancer on 32400 ?

**Comment by davidjameshowell** [comment] 2019-03-06 20:13
The transcoder Node server app - ffmpeg was throwing errors (will revert and grab them) and not configuring the internal transcoder port to be replaced appropriately. I just switched this to 32400 for the Node server (since everything is terminated by Traefik, no ports exposed out and is working as intended.

**Comment by Maxou44** [comment] 2019-03-06 20:17
Ok, I will close this issue ✌
Feel free to share your Docker files and configuration 👌

**Closed by Maxou44** 2019-03-06 20:17 UTC
